set_property IOSTANDARD LVCMOS18 [get_ports UART*]

#HD_GPIO_5 on FPGA / Connector pin 13 / UART1_rxd
set_property PACKAGE_PIN G5 [get_ports UART1_rxd]
#HD_GPIO_4 on FPGA / Connector pin 11 / UART1_txd
set_property PACKAGE_PIN F6 [get_ports UART1_txd]

set_property IOSTANDARD LVCMOS18 [get_ports BT*]

#BT_HCI_RTS on FPGA /  emio_uart0_ctsn connect to
set_property PACKAGE_PIN B7 [get_ports BT_ctsn]
#BT_HCI_CTS on FPGA / emio_uart0_rtsn
set_property PACKAGE_PIN B5 [get_ports BT_rtsn]

set_property PACKAGE_PIN D7 [get_ports {lcd_ctl[1]}]
set_property PACKAGE_PIN F8 [get_ports {lcd_ctl[2]}]
set_property PACKAGE_PIN F7 [get_ports {lcd_ctl[3]}]
set_property PACKAGE_PIN G7 [get_ports {lcd_ctl[4]}]
set_property PACKAGE_PIN E6 [get_ports {lcd_ctl[0]}]
set_property PACKAGE_PIN D6 [get_ports {lcd_data[0]}]
set_property PACKAGE_PIN D5 [get_ports {lcd_data[1]}]
set_property PACKAGE_PIN C7 [get_ports {lcd_data[2]}]
set_property PACKAGE_PIN A6 [get_ports {lcd_data[3]}]
set_property PACKAGE_PIN B6 [get_ports {lcd_data[4]}]
set_property PACKAGE_PIN A7 [get_ports {lcd_data[5]}]
set_property PACKAGE_PIN C5 [get_ports {lcd_data[6]}]
set_property PACKAGE_PIN G6 [get_ports {lcd_data[7]}]

set_property IOSTANDARD LVCMOS18 [get_ports {lcd_ctl[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_ctl[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_ctl[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_ctl[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_ctl[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_data[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_data[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_data[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_data[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_data[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_data[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_data[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {lcd_data[0]}]
set_property SLEW SLOW [get_ports {lcd_ctl[4]}]
set_property SLEW SLOW [get_ports {lcd_ctl[3]}]
set_property SLEW SLOW [get_ports {lcd_ctl[2]}]
set_property SLEW SLOW [get_ports {lcd_ctl[1]}]
set_property SLEW SLOW [get_ports {lcd_ctl[0]}]
set_property DRIVE 12 [get_ports {lcd_ctl[4]}]
set_property DRIVE 12 [get_ports {lcd_ctl[3]}]
set_property DRIVE 12 [get_ports {lcd_ctl[2]}]
set_property DRIVE 12 [get_ports {lcd_ctl[1]}]
set_property DRIVE 12 [get_ports {lcd_ctl[0]}]

set_property OFFCHIP_TERM NONE [get_ports lcd_ctl[4]]
set_property OFFCHIP_TERM NONE [get_ports lcd_ctl[3]]
set_property OFFCHIP_TERM NONE [get_ports lcd_ctl[2]]
set_property OFFCHIP_TERM NONE [get_ports lcd_ctl[1]]
set_property OFFCHIP_TERM NONE [get_ports lcd_ctl[0]]
set_property OFFCHIP_TERM NONE [get_ports lcd_data[7]]
set_property OFFCHIP_TERM NONE [get_ports lcd_data[6]]
set_property OFFCHIP_TERM NONE [get_ports lcd_data[5]]
set_property OFFCHIP_TERM NONE [get_ports lcd_data[4]]
set_property OFFCHIP_TERM NONE [get_ports lcd_data[3]]
set_property OFFCHIP_TERM NONE [get_ports lcd_data[2]]
set_property OFFCHIP_TERM NONE [get_ports lcd_data[1]]
set_property OFFCHIP_TERM NONE [get_ports lcd_data[0]]
set_property SLEW SLOW [get_ports {lcd_data[7]}]
set_property SLEW SLOW [get_ports {lcd_data[6]}]
set_property SLEW SLOW [get_ports {lcd_data[5]}]
set_property SLEW SLOW [get_ports {lcd_data[4]}]
set_property SLEW SLOW [get_ports {lcd_data[3]}]
set_property SLEW SLOW [get_ports {lcd_data[2]}]
set_property SLEW SLOW [get_ports {lcd_data[1]}]
set_property SLEW SLOW [get_ports {lcd_data[0]}]
